### ISSUE TITLE
Netbooks server link broken and Colon Cancer paths for files in tutorials not available

### ISSUE THREAD

**Issue by Surya-Upadhyayula** [netZoo/netbooks#9]
Hi,

Requesting to share the files used in the colon cancer notebook for study and execution. 
Also, the netbooks JupyterHub is not opening.

**Comment by marouenbg** [comment]
Hi @Surya-Upadhyayula ,

I believe this was resolved because you have a start. The server disconnects automatically after 1 hour of inactivity so you need to logout and create a new session because all files will be deleted. The logout file is on the upper right side corner of Jupyter notebook.

Please let me know if you need anything else!
Marouen

**Comment by Surya-Upadhyayula** [comment]
Hi,

Thanks. Solved.
